### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by joa-quim** [veracrypt/VeraCrypt-DCS#1]
Hi, 

I tried to build Vera but confess that I'm trouble. What is edk? And I do have nasm installed but the setenv.bat batch won't find it, see

```
where nasm
C:\programs\nasm-2.11.05\nasm.exe
C:\j\bin\nasm.exe

V:\VeraCrypt-DCS-master>echo %NASM_PREFIX%
c:\Tools\nasm\
```

also, when I run the setenv.bat it asks for a edksetup.bat that I do not know what it is

```
setenv.bat
Setting environment for using Microsoft Visual Studio 2010 x86 tools.
The system cannot find the path specified.
'edksetup.bat' is not recognized as an internal or external command,
operable program or batch file.
```

Thanks for any enlightenment

**Comment by idrassi** [comment]
Hi,

The instructions to build VeraCrypt-DCS are detailled here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Boot/EFI/Readme.txt

Just use tag "VeraCrypt_1.19" for the latest stable source instead of "VeraCrypt_1.18" mentioned in the file above.

One additional point: python must be installed on the system.

**Comment by Ameerme90** [comment]
> Hi,
> 
> The instructions to build VeraCrypt-DCS are detailled here: https://github.com/veracrypt/VeraCrypt/blob/master/src/Boot/EFI/Readme.txt
> 
> Just use tag "VeraCrypt_1.19" for the latest stable source instead of "VeraCrypt_1.18" mentioned in the file above.
> 
> One additional point: python must be installed on the system.

have installed python on system but still get message PYTHONHOME NOT Found!
Can you help me please
