### ISSUE TITLE
Error in Tpm20.c when compiling with VS2017

### ISSUE THREAD

**Issue by manison** [veracrypt/VeraCrypt-DCS#15]
When I'm building DcsTpmLib under VS2017 (#13), I get the following error in _Tpm20.c_:

> d:\shared\edk2\DcsPkg\Library\DcsTpmLib\Tpm20.c(544): error C2220: warning treated as error - no 'object' file generated
> d:\shared\edk2\DcsPkg\Library\DcsTpmLib\Tpm20.c(544): warning C4459: declaration of 'gCELine' hides global declaration
> d:\shared\edk2\DcsPkg\Include\Library/CommonLib.h(30): note: see declaration of 'gCELine'

I can see no re-declaration of `gCELine` variable [here](https://github.com/veracrypt/VeraCrypt-DCS/blob/master/Library/DcsTpmLib/Tpm20.c#L544).

Even if I look at preprocessed output, I can't see whats going on. The same `CE` macro a few lines above causes no problem.

I'm tempted to simply disable the warning, but I would like to know what's really going on. Can anybody share a hint?

**Comment by idrassi** [comment]
A little bit late....There was actually a typo mistake in the code that was causing this: the previous line was engine with a ',' instead of a ';' and that’s why gCELine ended up being declared as local variable.

I have fixed this issue with the following commit: https://github.com/veracrypt/VeraCrypt-DCS/commit/f2422d9f6cd13b9d8eac20ab8dc93841e5b8f209
