### ISSUE TITLE
Add valid ceritifcates for secure boot - instruction doesn't work

### ISSUE THREAD

**Issue by inliquid** [veracrypt/VeraCrypt-DCS#2]
Hi guys,

I am trying to follow these steps:

> 1. Enter BIOS configuration
> 2. Switch Secure boot to setup mode (or custom mode). It deletes PK (platform certificate) and allows to load DCS platform key.
> 3. Boot Windows
> 4. execute from admin command prompt
>    powershell -File sb_set_siglists.ps1

What I got after script is run:
```
PS C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot> powershell -File sb_set_siglists.ps1
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:4 знак:1
+ Set-SecureBootUEFI -Name PK -Time 2015-09-11 -Content $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:5 знак:1
+ Set-SecureBootUEFI -Name KEK -Time 2015-09-11 -Content $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:6 знак:1
+ Set-SecureBootUEFI -Name db -Time 2015-09-11 -Content $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:7 знак:1
+ Set-SecureBootUEFI -Name dbx -Time 2015-09-11 -Content $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Setting self-signed PK...
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:10 знак:1
+ Set-SecureBootUEFI -Time 2016-08-08T00:00:00Z -ContentFilePath siglis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Setting PK-signed KEK...
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:13 знак:1
+ Set-SecureBootUEFI -Time 2016-08-08T00:00:00Z -ContentFilePath siglis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Setting KEK-signed DCS cert in db...
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:16 знак:1
+ Set-SecureBootUEFI -Time 2016-08-08T00:00:00Z -ContentFilePath siglis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Setting KEK-signed MS cert in db...
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:19 знак:1
+ Set-SecureBootUEFI -Time 2016-08-08T00:00:00Z -ContentFilePath siglis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand

Setting KEK-signed MS UEFI cert in db...
Set-SecureBootUEFI : Неправильные данные проверки подлинности: 0xC0000022
C:\Users\*****\Downloads\VeraCrypt-DCS-master\SecureBoot\sb_set_siglists.ps1:22 знак:1
+ Set-SecureBootUEFI -Time 2016-08-08T00:00:00Z -ContentFilePath siglis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (Microsoft.Secur...BootUefiCommand:SetSecureBootUefiCommand) [Set-SecureBootUEFI], UnauthorizedAccessException
    + FullyQualifiedErrorId : SetFWVarFailed,Microsoft.SecureBoot.Commands.SetSecureBootUefiCommand
```

**Comment by inliquid** [comment]
After several tries with different approach some platform keys were updated, however Windows stopped booting and then computer have been bricked to black screen after reboot and necessety for motherboard bios repair. I would not recommend anyone to even try to make secure boot operating with VeraCrypt. And I think it's better to remove these non-working and dangerous instructions with huge piece of details missing.

**Comment by kosztyua** [comment]
Same issue here, and based on inliquid's experience I will stop trying to make this work. Please fix it!

**Comment by cerberii** [comment]
platform keys are not needed as your bios has minix at -3 level running, allowing access while the system is not even powered.

**Comment by idrassi** [comment]
The current script only loads our certificate plus two certificates from Microsoft but some manufactures (e.g HP) require that their own certificate be loaded since they run some EFI drivers at boot and if the certificate is not present the machine may not start at all.
I think this is what happened to @inliquid.
Is it possible to know which machine model?

In order to solve this, we need to have the most exhaustive possible
list of manufacturers certificates so that we can update Alex's script
to include them and this way SecureBoot can be activated without risk.

For this purpose, I have developed a command line tool that extracts
important EFI variables from the machine firmware and then create
several files and folders containing the machines firmware certificates
and EFI variables: a folder named "SigLists" and other folders whose
name is in GUID format (e.g. 77fa9abd-0359-4d32-bd60-28f4e78f784b).

The tool can be downloaded at
https://www.veracrypt.fr/downloads/tools/dumpEfiVars.exe (pgp signature:
https://www.veracrypt.fr/downloads/tools/dumpEfiVars.exe.sig). This tool
is signed using the same IDRIX certificates that are used to sign
VeraCrypt binaries.

I'm looking for users who can run this tool in their machines and then
post to this forum thread a zip containing the folders created by this
tool alongside information about the manufacturer of their machine.

On my side, I have retrieved necessary information for Asus and HP so
data for other manufacturers are needed (e.g. Acer, Dell, Fujitsu,
Lenovo, Toshiba...)

**Comment by Mogost** [comment]
@idrassi Also, why we need to use self-signed certificate?
Why veracrypt loader cannot be signed on https://sysdev.microsoft.com for example?

**Comment by idrassi** [comment]
First of all, Microsoft refuses to sign VeraCrypt-DCS bootloader because
it contains LGPL code. If you want it to be signed, a license change is
needed or a rewrite of most parts. For now, this is not possible.

Concerning the files generated by the tool dumpEfiVars, it safe to share
them because they contains only public data of the machine manufacturer.
You can explorer the files yourself and see that they are just
certificates and hashes (the tool dumps content to the console anyway).
I have also published the source code of the tool so that anybody can
check it and build it, you can find it at
https://github.com/veracrypt/dumpEfiVars.

I was not able to work lately on the script update because of personal
issues that I can not discuss publicly (I can share information using
secure communication). My idea is to gather certificates for major
manufacturers, sign them with our key and create necessary blobs to be
loaded into the machine.
Because of the logic complexity, I will probably develop a tool that
will embed all signed certificates and hashes and it will generate
PowerShell scripts depending on the machine configuration. Also, I want 
the tool to enable back-up of original configuration and restoring it if
needed.

As you can imagine, this takes time so probably a first step would be to
make available signed certificates and hashes so that technical users
can load certificates them selves.

Anyway, I will try to advance on this subject in the coming days
alongside the expected release of 1.23.

**Comment by Mogost** [comment]
@idrassi Thanks for your reply. Attached certificates for lenovo.
[lenovo_yoga720.zip](https://github.com/veracrypt/VeraCrypt-DCS/files/2089703/lenovo_yoga720.zip)

**Comment by idrassi** [comment]
I have pushed new modifIcations to the PowerShell script along side new certificates received from the community members who shared their EFI dumps.
This should fix the various errors encountered and which were caused by the order used to us date EFI variables (Thanks to user Alexander B. for sharing information at https://wiki.archlinux.org/index.php/Secure_Boot#Enroll_keys_in_firmware).

You can grab new script and certificates from SecureBoot folder or download a packaged zip from https://sourceforge.net/projects/veracrypt/files/Contributions/SecureBootVeraCrypt.zip/download (PGP signature at https://sourceforge.net/projects/veracrypt/files/Contributions/SecureBootVeraCrypt.zip.sig/download).

Please read Readme.txt for instructions that includes using dumpEfiVars.exe to identify machines specific EFI certificate so that PowerShell can be adapted accordingly.

@Mogost: Thank you for the dump which included a new Lenovo certificate and sorry for the delay. Concerning the license, Alex (@kavsrf) has wrote most of the bootloader code and for now he doesn’t want to change then license. He wants to protect his work while at the same time trying to find monetization solutions.
