### ISSUE TITLE
Some initial log errors when running sb_set_siglists.ps1

### ISSUE THREAD

**Issue by pjdv2** [veracrypt/VeraCrypt-DCS#3]
I just wanted to note that I followed the VeraCrypt-DCS/SecureBoot/readme.txt and can confirm that this works (that is, on my system and now having Secure Boot Enabled again). However, I did have some _red_ console output errors before it sets the platform and key exchange key. I didn't log them, so I can't share them, but maybe someone else can tell me what that was about and if it could have had any significance to the signing process of the bootloader files or otherwise, any side effects that may occur.

**Comment by idrassi** [comment]
Before setting the platform and key exchange key, the script tries to clear the EFI variables and it looks like this was not possible in your machine (strange by the way)

This doesn’t harm since the most important is that the setting the EFI variables succeeds and this is what happened in your case. So you have nothing to worry about.

**Comment by idrassi** [comment]
For those interested, the latest version of the PowerShell script can always be found at https://sourceforge.net/projects/veracrypt/files/Contributions/SecureBootVeraCrypt.zip/download
