### ISSUE TITLE
[UPDATE] Secure Boot files for Gigabyte GA-Z97-HD3

### ISSUE THREAD

**Issue by friedensfurz** [veracrypt/VeraCrypt-DCS#8]
Hello @idrassi ,
I noticed that there are no secure boot keys for my Gigabyte mainboard available,
so here are the necessary files in a ZIP.
Thanks 👍 
[Gigabyte-GA-Z97-HD3.zip](https://github.com/veracrypt/VeraCrypt-DCS/files/2328298/Gigabyte-GA-Z97-HD3.zip)

**Comment by idrassi** [comment]
Hi @friedensfurz,

Gigabyte mainboards come only with the default Microsoft keys that are
already present in the PowerShell script so there is no need for any
customization.
Your dump confirm this since it contains only entries for Microsoft keys.
You can run the PowerShell script after setting SecureBoot to custom
mode and your SecureBoot configuration will be updated correctly so that
VeraCrypt can run in SecureBoot mode.
